WebApplication6/Models/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication6.Models
{
    public class Person
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [MinLength(2, ErrorMessage = "Должно быть неменее 3 символов")]
        [MaxLength(20, ErrorMessage = "Отчество должна быть менее 20 символов")]
        public string Name { get; set; }
        [Required]
        [MinLength(2, ErrorMessage = "Должно быть неменее 3 символов")]
        [MaxLength(20, ErrorMessage = "Отчество должна быть менее 20 символов")]
        public string Family { get; set; }
        [MinLength(2, ErrorMessage = "Должно быть неменее 3 символов")]
        [MaxLength(20, ErrorMessage = "Отчество должна быть менее 20 символов")]
        public string Surname { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public string Foto { get; set; }
        public int Rate { get; set; }
        [MaxLength(2000, ErrorMessage = "Тест болжен быть менее 2000 символов")]
        public string WayToPolitics { get; set; }
        public string SubmittedId { get; set; }
        public int CityId { get; set; }

        public virtual ApplicationUser Submitted { get; set; }
        public virtual Party Party { get; set; }
        public virtual City City { get; set; }
        public virtual Position Position { get; set; }
        public virtual ICollection<Post> Posts { get; set; } 
        public virtual ICollection<PeoplesUsers> PersonUsers { get; set; }
        public virtual ICollection<PeopleComment> Comments { get; set; }
    }

    
}

WebApplication6/Controllers/PartyController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{
    public class PartyController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        protected UserManager<ApplicationUser> UserManager { get; set; }
        public PartyController()
        {
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.db));
        }
        // GET: Party
        public ActionResult Index()
        {
            return View();
        }

    }
}

WebApplication6/Controllers/PeopleController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{
    public class PeopleController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        /// <summary>
        /// User manager - attached to application DB context
        /// </summary>
        protected UserManager<ApplicationUser> UserManager { get; set; }
        public PeopleController()
        {
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.db));
        }
        // GET: People
        public ActionResult Index()
        {
            var AllowPositions = new List<string>() { "Народный депутат", "Министр", "Помошник Министра", "Мэр", "МВД" };
            var positions = db.Positions.Where(x => AllowPositions.Contains(x.Name)).ToList();
            var PeoplesPerPos = new Dictionary<Position, List<Person>>();
            foreach (var item in positions)
            {
                var temp = db.Persons.Where(x => x.Position.Id == item.Id)
                                    .OrderBy(x => x.Rate)
                                    .Take(15)
                                    .ToList();

                PeoplesPerPos.Add(item, temp);
            }
            if (User.Identity.IsAuthenticated)
            {
                var id = User.Identity.GetUserId();
                ViewBag.flags = db.PeopleUsers.Where(x => x.User.Id == id).ToList();
            }
            return View(new PersonIndexViewModel() { PeoplePerPosition = PeoplesPerPos });

        }
        public ActionResult Top(int page = 1)
        {
            int pageSize = 8; // количество объектов на страницу
            IEnumerable<Person> Persons = db.Persons.OrderBy(x => x.Rate).Skip((page - 1) * pageSize).Take(pageSize).ToList();
            if (User.Identity.IsAuthenticated)
            {
                Session["MainImg"] = UserManager.FindById(User.Identity.GetUserId()).MainImage;
                var id = User.Identity.GetUserId();
                ViewBag.flags = db.PeopleUsers.Where(x => x.User.Id == id).ToList();
                return View("Top", Persons);
            }
            return View("Top", Persons);
        }
        // GET: People/Details/5
        public ActionResult Details(int id)
        {

            Person person = db.Persons.FirstOrDefault(x => x.Id == id);
            if (person == null)
            {
                throw new HttpException(404, "NotFound");
            }
            var temp = db.PeopleUsers.FirstOrDefault(x => x.Person.Id == id);
            if (temp != null)
            {
                ViewBag.Like = db.PeopleUsers.Where(x => x.Person.Id == id).Sum(x => x.Like ? 1 : 0);
                ViewBag.DisLike = db.PeopleUsers.Where(x => x.Person.Id == id).Sum(x => x.DisLike ? 1 : 0);
            }
            else
            {
                ViewBag.Like = 0;
                ViewBag.DisLike = 0;
            }
            ViewBag.CriminalId = db.Tags.FirstOrDefault(x => x.Name == "криминал").Id;
            ViewBag.GoodJobId = db.Tags.FirstOrDefault(x => x.Name == "хорошие дела").Id;
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.Identity.GetUserId();
                ViewBag.UserName = UserManager.Users.First(x => x.Id == userId).Name;
            }
            return View(person);
        }
        public ActionResult Info(int id)
        {
            Person person = db.Persons.FirstOrDefault(x => x.Id == id);
            if (person == null)
            {
                throw new HttpException(404, "Not found");
            }

            if (person.WayToPolitics != null)
            {
                if (person.WayToPolitics != "")
                {
                    ViewBag.WayToPolit = person.WayToPolitics.Split('\n');
                }
                else
                {
                    ViewBag.WayToPolit = "";
                }
            }
            else
            {
                ViewBag.WayToPolit = "";
            }
            return View(person);
        }

        // GET: People/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.Cities = db.Cities.Select(x => new { Id = x.Id, Name = x.Name }).ToList();
            ViewBag.Parties = db.Parties.Select(x => new { Id = x.Id, Name = x.Name }).ToList();
            return View();
        }

        // POST: People/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Family,Surname,Date,Foto")] Person person)
        {
            if (ModelState.IsValid)
            {
                person.Submitted = UserManager.FindById(User.Identity.GetUserId());
                db.Persons.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }
        [Authorize(Roles = "Admin, Moderator")]
        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                throw new HttpException(404, "Not found");
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                throw new HttpException(404, "Not found");
            }
            return View(person);
        }


        // POST: People/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Moderator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Family,Surname,Date,Foto,Rate")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: People/Delete/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Delete(int id)
        {
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                throw new HttpException(404, "Not found");
            }
            return View(person);
        }
        // POST: People/Delete/5
        [Authorize(Roles = "Admin, Moderator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.Persons.Find(id);
            db.Persons.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Auth]
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult Like(int id)
        {
            var people = db.Persons.Where(x => x.Id == id).FirstOrDefault();
            if (people == null)
            {
                return Json(new { error = "404" }, JsonRequestBehavior.AllowGet);
            }
            else if (!User.Identity.IsAuthenticated)
            {
                return Json(new { error = "login" }, JsonRequestBehavior.AllowGet);
            }
            var userId = User.Identity.GetUserId();
            var UserTemp = db.PeopleUsers.FirstOrDefault(x => x.User.Id == userId && x.Person.Id == id);
            if (UserTemp != null)
            {
                if (UserTemp.Like)
                {
                    return Json(new { rate = people.Rate, flag = 1, id = id }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    if (UserTemp.DisLike)
                    {
                        people.Rate += 1;
                        UserTemp.Like = false;
                        UserTemp.DisLike = false;
                        db.SaveChanges();
                        return Json(new { rate = people.Rate, flag = 0, id = id }, JsonRequestBehavior.AllowGet);

                    }
                    people.Rate += 1;
                    UserTemp.Like = true;
                    UserTemp.DisLike = false;
                    db.SaveChanges();
                    return Json(new { rate = people.Rate, flag = 1, id = id }, JsonRequestBehavior.AllowGet);
                }
            }
            people.Rate += 1;
            var user = UserManager.FindById(userId);
            db.PeopleUsers.Add(new PeoplesUsers() { Person = people, User = user, Like = true, DisLike = false });
            db.SaveChanges();
            return Json(new { rate = people.Rate, flag = 1, id = id }, JsonRequestBehavior.AllowGet);
        }

        [Auth]
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult DisLike(int id)
        {
            var people = db.Persons.Where(x => x.Id == id).FirstOrDefault();
            if (people == null)
            {
                return Json(new { error = "404" }, JsonRequestBehavior.AllowGet);
            }
            else if (!User.Identity.IsAuthenticated)
            {
                return Json(new { error = "Login" }, JsonRequestBehavior.AllowGet);
            }
            var userId = User.Identity.GetUserId();
            var UserTemp = db.PeopleUsers.FirstOrDefault(x => x.User.Id == userId && x.Person.Id == id);

            if (UserTemp != null)

WebApplication6/Controllers/SearchController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication6.Models;
using PagedList.Mvc;
using PagedList;
namespace WebApplication6.Controllers
{
    public class SearchController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UserManager<ApplicationUser> UserManager { get; set; }
        public SearchController()
        {
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.db));
        }
        // GET: Search
        public ActionResult PeopleSearch(SearchStringViewModel model, int? page)
        {
            if (ModelState.IsValid)
            {
                int pageSize = 8;
                int pageNumber = (page ?? 1);
                var Peoples = db.Persons.Where(x => x.Family.Contains(model.SearchString) ||
                                                    x.Name.Contains(model.SearchString) ||
                                                    x.Surname.Contains(model.SearchString)
                                                    ).OrderBy(x=>x.Family);
                ViewBag.returnAction = "PeopleSearch";
                
                if (User.Identity.IsAuthenticated)
                {
                    var Userid = User.Identity.GetUserId();
                    ViewBag.flags = db.PeopleUsers.Where(x => x.User.Id == Userid).ToList();
                }
                return View("Index", Peoples.ToPagedList(pageNumber, pageSize));

            }
            return View("Index",new List<Person>().ToPagedList(8,8));
        }

        public ActionResult PositionSearch(int id, int? page)
        {
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            ViewBag.returnAction = "PositionSearch";
            if (User.Identity.IsAuthenticated)
            {
                var Userid = User.Identity.GetUserId();
                ViewBag.flags = db.PeopleUsers.Where(x => x.User.Id == Userid).ToList();
            }
            return View("Index", db.Persons.Where(x => x.Position.Id == id)
                                           .OrderBy(x => x.Family)
                                           .ToPagedList(pageNumber, pageSize));
        }
        public ActionResult PartySearch(int id, int? page)
        {
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            ViewBag.returnAction = "PartySearch";
            if (User.Identity.IsAuthenticated)
            {
                var Userid = User.Identity.GetUserId();
                ViewBag.flags = db.PeopleUsers.Where(x => x.User.Id == Userid).ToList();
            }
            return View("Index", db.Persons.Where(x => x.Party.Id == id)
                                           .OrderBy(x => x.Family)
                                           .ToPagedList(pageNumber, pageSize)
                                           );
        }
        public ActionResult TagsSearch(int id, int? page)
        {
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            var Tag = db.Tags.First(x => x.Id == id);
            ViewBag.returnAction = "TagsSearch";
            if (User.Identity.IsAuthenticated)
            {
                var Userid = User.Identity.GetUserId();
                ViewBag.flags = db.PeopleUsers.Where(x => x.User.Id == Userid).ToList();
            }
            return View("PostsSearch", db.Posts.Where(x => x.Tags.Contains(Tag))
                                               .OrderBy(x => x.PostedOn)
                                               .ToPagedList(pageNumber, pageSize));
        }
    }

}

WebApplication6/Views/People/Card.cshtml
@model  WebApplication6.Models.Person
@using WebApplication6.Models;

@{
    List<PeoplesUsers> flag = ViewBag.flags;
    var colorDislike = "";
    var colorLike = "";
}

<div class="card">
    <div class="card-body">
        <a href=@Url.Action("Details", "People", new { id = Model.Id })>
            <img src='~/Content/@Model.Foto' class="card-img-top" />
        </a>
        <div class="rate">
            @if (User.Identity.IsAuthenticated)
            {

                var temp = flag.FirstOrDefault(x => x.Person == Model);

                if (temp != null)
                {
                    if (temp.DisLike)
                    {
                        colorDislike = "red";
                    }
                    else if (temp.Like)
                    {
                        colorLike = "green";
                    }
                }
            }
            @Ajax.RawActionLink(String.Format("<i class='fa fa-thumbs-up {0}' id='Like{1}'></i>", colorLike, Model.Id), "Like", "People", new { id = Model.Id },
                    new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "LikeSucces" }, new { });
            @Ajax.RawActionLink(String.Format("<i class='fa fa-thumbs-down {0}' id='DisLike{1}'></i>", colorDislike, Model.Id), "DisLike", "People", new { id = Model.Id },
                    new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "DisLikeSucces" }, new { });

        </div>
        <div class="count-body">
            @if (Model.Rate <= 0)
            {
                <p class='count red' id=@String.Format("LikeCounter{0}", Model.Id)>@Model.Rate</p>
            }
            else
            {
                <p class='count green' id=@String.Format("LikeCounter{0}", Model.Id)>@Model.Rate</p>
            }
        </div>
        <div class="card-title">
            @Html.DisplayFor(Model => Model.Name)
            @Html.DisplayFor(Model => Model.Family)
            @Html.DisplayFor(Model => Model.Surname)
        </div>
        <div class="position">
            @Html.DisplayFor(Model => Model.Position.Name)
        </div>
    </div>
</div>

WebApplication6/Views/People/Create.cshtml
@model WebApplication6.Models.Person
<div class="people-create-wraper">
    @if (User.IsInRole("Admin"))
    {
        using (Html.BeginForm("Create", "People", FormMethod.Post, new { @class = "login_form", role = "form", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="people-create-form">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <ul class="form-group">
                    <div class="row">
                        <div id="dropZone">
                            Для загрузки, перетащите файл сюда.
                        </div>
                        <input type="file" id="file" name="Foto" style="display:none; visibility:hidden" />
                    </div>
                    <div class="row">
                        <li>
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "name-help" })
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "inp", @placeholder = "Имя" } })
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.Family, "", new { @class = "family-help" })
                            @Html.EditorFor(model => model.Family, new { htmlAttributes = new { @class = "inp", @placeholder = "Фамилия" } })
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "surname-help" })
                            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "inp", @placeholder = "Отчество" } })
                        </li>

                    </div>
                    <div class="row">
                        <li>
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "politic-text" })
                            <input type="date" id="people-date" class="inp" name="Date" />
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "surname-help" })
                            @Html.ListBox("Cities", new SelectList(ViewBag.Cities, "Id", "Name"), new { @class = "cities-dropdown inp" })
                        </li>
                        <li>
                            @Html.ValidationMessageFor(model => model.Party, "", new { @class = "surname-help" })
                            @Html.ListBox("Parties", new SelectList(ViewBag.Parties, "Id", "Name"), new { @class = "cities-dropdown inp" })
                        </li>
                    </div>
                </ul>
                @Html.ValidationMessageFor(model => model.WayToPolitics, "", new { @class = "politic-text" })
                @Html.TextArea("WayToPolitics", "", new { @class = "people-text-input", @placeholder = "Биография" })

                <input type="submit" value="Create" class="enter-btn" />

            </div>
        }
    }
    else
    {
        <h2>Вы не являетель администратором</h2>
    }
</div>

WebApplication6/Views/People/Delete.cshtml
@model WebApplication6.Models.Person

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Family)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Family)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Surname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Foto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Foto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication6/Views/People/Index.cshtml
@model WebApplication6.Models.PersonIndexViewModel
@using WebApplication6.Models;

<div class="card-deck">
    @foreach (var Mainitem in Model.PeoplePerPosition)
    {
    <h2 class="position-name"><a href="@Url.Action("Index", "Positions", new {id = Mainitem.Key.Id })">@Mainitem.Key.Name</a> </h2>
    <div class="slider">
        @foreach (var item in Mainitem.Value)
        {
            @Html.Partial("../People/Card", item);
        }
    </div>
    }
</div>

WebApplication6/Views/People/Info.cshtml
@model WebApplication6.Models.Person
@{
    Layout = "";
}
<div class="info-content">
    <h1>@Model.Family @Model.Name @Model.Surname </h1>
    <p> Дата рождения:<span class="color-gray"> @Model.Date.ToShortDateString()</span></p>
    <p> Родился:<span class="color-gray"> @Model.City.Name</span></p>
    <div> Партии:<span class="color-orange"> <a href="@Url.Action("PartySearch","Search",new {id = Model.Party.Id})">@Model.Party.Name</a></span></div>
    <div> Должность: <span class="color-orange"><a href="@Url.Action("PositionSearch","Search", new {id = Model.Position.Id })"> @Model.Position.Name</a></span></div>
    <p> Путь к власти: </p>
    @foreach (var item in ViewBag.WayToPolit)
    {
        <p><span class="color-gray">item</span></p>
    }
</div>
<div class="comments">
    @if (User.Identity.IsAuthenticated)
    {
        /*var a = */
        @Html.Action("Index", "PeopleComments", new { id = Model.Id });
            @*var str = a.ToHtmlString();
            @Html.Raw(str)*@
    }
    else
    {
        <h2 class="no-item">Пожалуйста введите логин и пароль</h2>   
    }
</div>

WebApplication6/Views/People/Search.cshtml
@model WebApplication6.Models.SearchViewModel
@using WebApplication6.Models;
@{
    List<PeoplesUsers> flag = ViewBag.flags;
}
<div class="search-card-deck">
    @if (Model.Persons.Count() != 0)
    {

        foreach (var item in Model.Persons)
        {
            <div class="search-card">
                <div class="search-card-body">
                    <a href=@Url.Action("Details", "People", new { id = item.Id })>
                        <img src='~/Content/@item.Foto' class="search-card-img-top" />
                    </a>
                    <div class="rate">
                        @if (User.Identity.IsAuthenticated)
                        {

                            var temp = flag.FirstOrDefault(x => x.Person == item);

                            if (temp != null)
                            {

                                if (temp.DisLike)
                                {
                                    @Ajax.RawActionLink(String.Format("<i class='fa fa-thumbs-up' id='Like{0}'></i>", @item.Id), "Like", "People", new { id = @item.Id },
                                                                  new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "LikeSucces" }, new { });
                                    @Ajax.RawActionLink(String.Format("<i class='red fa fa-thumbs-down 'id='DisLike{0}'></i>", @item.Id), "DisLike", "People", new { id = @item.Id },
                                                                 new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "DisLikeSucces" }, new { });
                                }
                                else if (temp.Like)
                                {
                                    @Ajax.RawActionLink(String.Format("<i class='fa fa-thumbs-up green ' id='Like{0}'></i>", @item.Id), "Like", "People", new { id = @item.Id },
                                                                  new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "LikeSucces" }, new { });
                                    @Ajax.RawActionLink(String.Format("<i class='fa fa-thumbs-down 'id='DisLike{0}'></i>", @item.Id), "DisLike", "People", new { id = @item.Id },
                                                                 new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "DisLikeSucces" }, new { });
                                }
                                else
                                {
                                    @Ajax.RawActionLink(String.Format("<i class='fa fa-thumbs-up' id='Like{0}'></i>", @item.Id), "Like", "People", new { id = @item.Id },
                                                  new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "LikeSucces" }, new { });
                                    @Ajax.RawActionLink(String.Format("<i class='fa fa-thumbs-down 'id='DisLike{0}'></i>", @item.Id), "DisLike", "People", new { id = @item.Id },
                                                 new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "DisLikeSucces" }, new { });
                                }
                            }
                            else
                            {
                                @Ajax.RawActionLink(String.Format("<i class='fa fa-thumbs-up' id='Like{0}'></i>", @item.Id), "Like", "People", new { id = @item.Id },
                                                  new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "LikeSucces" }, new { });
                                @Ajax.RawActionLink(String.Format("<i class='fa fa-thumbs-down 'id='DisLike{0}'></i>", @item.Id), "DisLike", "People", new { id = @item.Id },
                                                 new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "DisLikeSucces" }, new { });
                            }
                        }
                        else
                        {
                            @Ajax.RawActionLink(String.Format("<i class='fa fa-thumbs-up' id='Like{0}'></i>", @item.Id), "Like", "People", new { id = @item.Id },
                                      new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "LikeSucces" }, new { });
                            @Ajax.RawActionLink(String.Format("<i class='fa fa-thumbs-down' id='DisLike{0}'></i>", @item.Id), "DisLike", "People", new { id = @item.Id },
                                      new AjaxOptions { OnFailure = "OnFailure", OnSuccess = "DisLikeSucces" }, new { });
                        }
                    </div>
                    <div class="count-body">
                        @if (item.Rate <= 0)
                        {
                            <p class='count red' id=@String.Format("LikeCounter{0}", item.Id)>@item.Rate</p>
                        }
                        else
                        {
                            <p class='count green' id=@String.Format("LikeCounter{0}", item.Id)>@item.Rate</p>
                        }
                    </div>
                </div>
                <div class="search-info-desk">
                    <div class="card-title">
                        @Html.DisplayFor(Model => item.Name)
                        @Html.DisplayFor(Model => item.Family)
                        @Html.DisplayFor(Model => item.Surname)
                    </div>
                    <div class="position">
                        @Html.DisplayFor(Model => item.Position.Name)
                    </div>
                    <a href=@Url.Action("Index", "Party", new { id = item.Id })>
                        <div class="party"> @item.Party.Name</div>
                    </a>
                    <div class="post-tags">
                        <ul>
                            @foreach (var tag in item.Posts.SelectMany(x => x.Tags))
                            {
                                <li> @tag.Name </li>
                            }
                        </ul>
                    </div>
                </div>

            </div>

        }
        <div class="pagination">
            @Html.PageLinks(Model.PageInfo, x => Url.Action("Search", new { page = x }), new { })
        </div>

    }
    else
    {
        <h2>Нечего не найдено</h2>
    }

</div>

WebApplication6/Views/People/Top.cshtml
@model IEnumerable<Person>
@using WebApplication6.Models;

<div class="card-deck-position">
    <div class="row">
        @foreach (var item in Model.Take(4))
        {
            @Html.Partial("../People/Card", item);
        }
    </div>
    <div class="row">
        @foreach (var item in Model.Skip(4))
        {
            @Html.Partial("../People/Card", item);
        }
    </div>
</div>