WebApplication6/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication6.Models
{
    public class Post
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public virtual int PostId { get; set; }
        [Required]
        public virtual string Title { get; set; }
        public virtual DateTime PostedOn { get; set; }
        public virtual DateTime? Modified { get; set; }
        public virtual string PostFile { get; set; }
        public virtual string UserId { get; set; }
        public virtual int PersonId { get; set; }
        public virtual ApplicationUser User { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<PostDescription> Description { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<PostComment> PostComment { get; set; }

    }
}

WebApplication6/Controllers/PeopleController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{
    public class PeopleController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        /// <summary>
        /// User manager - attached to application DB context
        /// </summary>
        protected UserManager<ApplicationUser> UserManager { get; set; }
        public PeopleController()
        {
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.db));
        }
        // GET: People
        public ActionResult Index()
        {
            var AllowPositions = new List<string>() { "Народный депутат", "Министр", "Помошник Министра", "Мэр", "МВД" };
            var positions = db.Positions.Where(x => AllowPositions.Contains(x.Name)).ToList();
            var PeoplesPerPos = new Dictionary<Position, List<Person>>();
            foreach (var item in positions)
            {
                var temp = db.Persons.Where(x => x.Position.Id == item.Id)
                                    .OrderBy(x => x.Rate)
                                    .Take(15)
                                    .ToList();

                PeoplesPerPos.Add(item, temp);
            }
            if (User.Identity.IsAuthenticated)
            {
                var id = User.Identity.GetUserId();
                ViewBag.flags = db.PeopleUsers.Where(x => x.User.Id == id).ToList();
            }
            return View(new PersonIndexViewModel() { PeoplePerPosition = PeoplesPerPos });

        }
        public ActionResult Top(int page = 1)
        {
            int pageSize = 8; // количество объектов на страницу
            IEnumerable<Person> Persons = db.Persons.OrderBy(x => x.Rate).Skip((page - 1) * pageSize).Take(pageSize).ToList();
            if (User.Identity.IsAuthenticated)
            {
                Session["MainImg"] = UserManager.FindById(User.Identity.GetUserId()).MainImage;
                var id = User.Identity.GetUserId();
                ViewBag.flags = db.PeopleUsers.Where(x => x.User.Id == id).ToList();
                return View("Top", Persons);
            }
            return View("Top", Persons);
        }
        // GET: People/Details/5
        public ActionResult Details(int id)
        {

            Person person = db.Persons.FirstOrDefault(x => x.Id == id);
            if (person == null)
            {
                throw new HttpException(404, "NotFound");
            }
            var temp = db.PeopleUsers.FirstOrDefault(x => x.Person.Id == id);
            if (temp != null)
            {
                ViewBag.Like = db.PeopleUsers.Where(x => x.Person.Id == id).Sum(x => x.Like ? 1 : 0);
                ViewBag.DisLike = db.PeopleUsers.Where(x => x.Person.Id == id).Sum(x => x.DisLike ? 1 : 0);
            }
            else
            {
                ViewBag.Like = 0;
                ViewBag.DisLike = 0;
            }
            ViewBag.CriminalId = db.Tags.FirstOrDefault(x => x.Name == "криминал").Id;
            ViewBag.GoodJobId = db.Tags.FirstOrDefault(x => x.Name == "хорошие дела").Id;
            if (User.Identity.IsAuthenticated)
            {
                var userId = User.Identity.GetUserId();
                ViewBag.UserName = UserManager.Users.First(x => x.Id == userId).Name;
            }
            return View(person);
        }
        public ActionResult Info(int id)
        {
            Person person = db.Persons.FirstOrDefault(x => x.Id == id);
            if (person == null)
            {
                throw new HttpException(404, "Not found");
            }

            if (person.WayToPolitics != null)
            {
                if (person.WayToPolitics != "")
                {
                    ViewBag.WayToPolit = person.WayToPolitics.Split('\n');
                }
                else
                {
                    ViewBag.WayToPolit = "";
                }
            }
            else
            {
                ViewBag.WayToPolit = "";
            }
            return View(person);
        }

        // GET: People/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.Cities = db.Cities.Select(x => new { Id = x.Id, Name = x.Name }).ToList();
            ViewBag.Parties = db.Parties.Select(x => new { Id = x.Id, Name = x.Name }).ToList();
            return View();
        }

        // POST: People/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Family,Surname,Date,Foto")] Person person)
        {
            if (ModelState.IsValid)
            {
                person.Submitted = UserManager.FindById(User.Identity.GetUserId());
                db.Persons.Add(person);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }
        [Authorize(Roles = "Admin, Moderator")]
        // GET: People/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                throw new HttpException(404, "Not found");
            }
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                throw new HttpException(404, "Not found");
            }
            return View(person);
        }


        // POST: People/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Moderator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Family,Surname,Date,Foto,Rate")] Person person)
        {
            if (ModelState.IsValid)
            {
                db.Entry(person).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(person);
        }

        // GET: People/Delete/5
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult Delete(int id)
        {
            Person person = db.Persons.Find(id);
            if (person == null)
            {
                throw new HttpException(404, "Not found");
            }
            return View(person);
        }
        // POST: People/Delete/5
        [Authorize(Roles = "Admin, Moderator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Person person = db.Persons.Find(id);
            db.Persons.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Auth]
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult Like(int id)
        {
            var people = db.Persons.Where(x => x.Id == id).FirstOrDefault();
            if (people == null)
            {
                return Json(new { error = "404" }, JsonRequestBehavior.AllowGet);
            }
            else if (!User.Identity.IsAuthenticated)
            {
                return Json(new { error = "login" }, JsonRequestBehavior.AllowGet);
            }
            var userId = User.Identity.GetUserId();
            var UserTemp = db.PeopleUsers.FirstOrDefault(x => x.User.Id == userId && x.Person.Id == id);
            if (UserTemp != null)
            {
                if (UserTemp.Like)
                {
                    return Json(new { rate = people.Rate, flag = 1, id = id }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    if (UserTemp.DisLike)
                    {
                        people.Rate += 1;
                        UserTemp.Like = false;
                        UserTemp.DisLike = false;
                        db.SaveChanges();
                        return Json(new { rate = people.Rate, flag = 0, id = id }, JsonRequestBehavior.AllowGet);

                    }
                    people.Rate += 1;
                    UserTemp.Like = true;
                    UserTemp.DisLike = false;
                    db.SaveChanges();
                    return Json(new { rate = people.Rate, flag = 1, id = id }, JsonRequestBehavior.AllowGet);
                }
            }
            people.Rate += 1;
            var user = UserManager.FindById(userId);
            db.PeopleUsers.Add(new PeoplesUsers() { Person = people, User = user, Like = true, DisLike = false });
            db.SaveChanges();
            return Json(new { rate = people.Rate, flag = 1, id = id }, JsonRequestBehavior.AllowGet);
        }

        [Auth]
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult DisLike(int id)
        {
            var people = db.Persons.Where(x => x.Id == id).FirstOrDefault();
            if (people == null)
            {
                return Json(new { error = "404" }, JsonRequestBehavior.AllowGet);
            }
            else if (!User.Identity.IsAuthenticated)
            {
                return Json(new { error = "Login" }, JsonRequestBehavior.AllowGet);
            }
            var userId = User.Identity.GetUserId();
            var UserTemp = db.PeopleUsers.FirstOrDefault(x => x.User.Id == userId && x.Person.Id == id);

            if (UserTemp != null)

WebApplication6/Controllers/PostsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using WebApplication6.Models;

namespace WebApplication6.Controllers
{

    [Auth]
    public class PostsController : Controller
    {
        
        private ApplicationDbContext db = new ApplicationDbContext();
        protected UserManager<ApplicationUser> UserManager { get; set; }
        public PostsController()
        {
            this.UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(this.db));
        }

        // GET: Posts 
        // Tag had to state criminal 
        // Tag
        [AllowAnonymous]
        public ActionResult Index(int Id, int TagId, int page = 1 )
        {
            var tag = db.Tags.FirstOrDefault(x => x.Id == TagId);
            if (tag == null)
            {
                return HttpNotFound();
            }
            int pageSize = 2; // количество объектов на страницу
            IEnumerable<Post> Posts = db.Posts.Where(x => x.PersonId == Id && x.Tags.FirstOrDefault(y => y.Id == tag.Id) != null).
                                                       OrderBy(x => x.PostId).Skip((page - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.postType = tag.Name;
            ViewBag.TagId = TagId;

            return View(Posts);
        }

        // GET: Posts 
        [AllowAnonymous]
        public ActionResult Details(int id, int TagId, string message="")
        {
            if (message != "")
            {
                ViewBag.message = message;
            }   
            var post = db.Posts.FirstOrDefault(x => x.PostId == id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.postType =  db.Tags.FirstOrDefault(x => x.Id == TagId).Name;
            ViewBag.personId = post.PersonId;
          
            return View(post);
        }
        // GET: Posts/Create
        public ActionResult Create(int TagId, int peopleId)
        {
            var postType = db.Tags.Where(x => x.Id == TagId).FirstOrDefault();
            if (postType==null)
            {
                return HttpNotFound();
            }

            return View("Create",new PostCreateViewModel() { PostType= postType.Id ,PersonId=peopleId});
        }

        // POST: Posts/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        // добавить создание файла по дате поста и папку картинки в ней

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public JsonResult Create(PostCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var postType = db.Tags.FirstOrDefault(x => x.Id == model.PostType);
                Post postTemp;
                var orderList = new List<PostDescription>();
                
                foreach (var item in model.Order)
                {
                    var type = Regex.Replace(item.Key, "[0-9]", string.Empty);
                    var temp = new PostDescription() { Type = type, Content = item.Value };
                    orderList.Add(temp);
                }

                var tagsTemp = new List<Tag>();
                tagsTemp.Add(postType);
                foreach (var item in model.Tags.Split(','))
                {
                    tagsTemp.Add(new Tag() { Name = item });
                }

                if (model.Files != null)
                {
                    string FileFolderPath;
                    //проверяем дерикторию создвем если нет 
                    FileFolderPath = DateTime.Now.ToString("ddMMyyyyHHmmss");
                    if (!Directory.Exists(Server.MapPath(FileFolderPath)))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/PostContent/" + FileFolderPath));
                    }

                    //сохраняем файлы
                    foreach (HttpPostedFileBase file in model.Files)
                    {
                        if (file.ContentLength > 0)
                        {
                            file.SaveAs(Server.MapPath("~/Content/PostContent/" + FileFolderPath + "/" + file.FileName));
                        }
                    }
                    postTemp = new Post()
                    {
                        Title = model.Title,
                        UserId = User.Identity.GetUserId(),
                        PersonId = model.PersonId,
                        PostedOn = DateTime.Now,
                        Description = orderList,
                        Tags = tagsTemp,
                        PostFile = FileFolderPath
                    };
                }
                else
                {
                    postTemp = new Post()
                    {
                        Title = model.Title,
                        UserId = User.Identity.GetUserId(),
                        PersonId = model.PersonId,
                        PostedOn = DateTime.Now,
                        Description = orderList,
                        Tags = tagsTemp,
                    };
                }

                foreach (var item in tagsTemp)
                {
                    if (db.Tags.FirstOrDefault(x=>x.Name==item.Name)==null)
                    {
                        db.Tags.Add(item);
                    }
                }
                db.Posts.Add(postTemp);
                db.SaveChanges();
               
                return Json(new {postTemp.PostId, TagId = model.PostType,  message = "Пост успешно добавлен" }, JsonRequestBehavior.AllowGet);
            }

            return ModelState.JsonValidation();
        }
        
        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            if (post.UserId!=User.Identity.GetUserId())
            {
                return HttpNotFound();
            }
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication6/Views/Posts/Create.cshtml
@model WebApplication6.Models.PostCreateViewModel
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="wrapper-post">
    @Html.ValidationMessageFor(m => m.Title, "", new { @class = "validation-massage" })
    @Html.TextBoxFor(m => m.Title, new { @class = "inp", @id = "title", @placeholder = "Введите заголовок" })

    <div class="post-content" id="tab-content">
    </div>
    <div class="add">
        <div class="add-container">
            <div class="add-text"> </div>
            <div class="add-img"><i class="fa fa-camera"></i></div>
        </div>
    </div>
    @Html.ValidationMessageFor(m => m.Tags, "", new { @class = "validation-massage" })
    @Html.TextBoxFor(m => m.Tags, new { @class = "inp", @id = "tags", @placeholder = "Введите несколько тегов через запятую" })

    @using (Html.BeginForm("Create", "Posts", FormMethod.Post, new { @id = "PostForm", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.PostType, new { @id = "PostType"})
        @Html.HiddenFor(m => m.PersonId, new { @id = "PersonId"})

        <input type="submit" id="submit" value="Добавить пост" />
    }
</div>

WebApplication6/Views/Posts/Delete.cshtml
@model WebApplication6.Models.Post

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Post</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.User.MainImage)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.User.MainImage)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.PostedOn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.PostedOn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Modified)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Modified)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

WebApplication6/Views/Posts/Details.cshtml
@using WebApplication6.Models;
@model WebApplication6.Models.Post
@{ 
    string postType = @ViewBag.postType;
    string message = @ViewBag.message;
}
<script>
 
</script>
<div class="post-wrapper">
    @if (message != null)
    {
        <p class="text-success">@message</p>
    }
    @Html.RawActionLink("<h2 class='go-back' ><i class='fa  fa-angle-double-left'></i>Назад</h2>", "Details", "People", new { id = ViewBag.personId }, new { })
    <h2 class="post-header">@Model.Title</h2>
    <div class="post-option">
        @if (Model.User.MainImage == null)
        {
            <i class="fa fa-user-circle" aria-hidden="true"></i>
        }
        else
        {
            <img class="avatar_small" src="@Url.Action("../Content/Userimg/" + Model.User.MainImage)" />
        }
        <span class="user_nick"> @Model.User.UserName </span> <span class="date"> @Model.PostedOn.ToString("dd/MM/yyyy HH:mm:ss")</span>
    </div>
    <div class="post-description">
        <div class="post-description-content">
            @foreach (var descitem in Model.Description)
            {
                if (descitem.Type == "img")
                {
                    <img src="@string.Format("/Content/PostContent/{0}/{1}",Model.PostFile, descitem.Content)" class="post-img" />
                }
                else if (descitem.Type == "text")
                {
                    <p class="post-text">@descitem.Content</p>
                }
            }
        </div>
    </div>
    <div class="post-tags">
        <ul>
            @foreach (var tag in Model.Tags)
            {
                if (tag.Name != postType)
                {
                    <li>
                        <a href="@Url.Action("TagSearch","Search",new {id = tag.Id})">
                            <span class="color-gray">
                                @tag.Name
                            </span>
                        </a>
                    </li>
                }

            }
        </ul>
    </div>
    <div class="comments">

        @if (User.Identity.IsAuthenticated)
        {
            @Html.Action("Index", "PostComments", new { id = ViewBag.personId });

        }
        else
        {
            <div class="no-item">Пожалуйста введите логин и пароль</div>
        }
    </div>
</div>

WebApplication6/Views/Posts/Edit.cshtml
@model WebApplication6.Models.Post

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Post</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.PostId)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.PostedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PostedOn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PostedOn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Modified, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Modified, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Modified, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

WebApplication6/Views/Posts/Index.cshtml
@model IEnumerable<WebApplication6.Models.Post>
@{
    Layout = null;
    string postType = @ViewBag.postType;
}
@if (Model.Count() != 0)
{
    foreach (var item in Model)
    {
        <li>
            <a href="@Url.Action("Details","Posts",new {id=item.PostId, TagId=ViewBag.TagId})"><h2 class="post-header">@item.Title</h2></a>
            <div class="post-option">
                @if (@item.User.MainImage == null)
                {
                    <i class="fa fa-user-circle" aria-hidden="true"></i>
                }
                else
                {
                    <img class="avatar_small" src="@Url.Action("../Content/Userimg/" + @item.User.MainImage)" />
                }
                <span class="user_nick"> @item.User.UserName </span> <span class="date">@item.PostedOn.ToString("dd/MM/yyyy HH:mm:ss")</span>
            </div>
            <div class="post-description">
                <div class="post-description-content">
                    @foreach (var descitem in item.Description)
                    {
                        if (descitem.Type == "img")
                        {
                            <img src="@Url.Action(string.Format("../Content/PostContent/{0}/{1}",item.PostFile, descitem.Content))" class="post-img" />
                        }
                        else if (descitem.Type == "text")
                        {
                            <p class="post-text">@descitem.Content</p>
                        }
                    }
                </div>
            </div>
            <div class="post-tags">
                <ul>
                    @foreach (var tag in item.Tags)
                    {
                        if (tag.Name != postType)
                        {
                            <li>
                                <a href="@Url.Action("TagSearch","Search",new {id = tag.Id})">
                                    <span class="color-gray">
                                        @tag.Name
                                    </span>
                                </a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </li>
    }

}
else
{
    <h2 class="no-item">Здесь пока что нет ни одного поста</h2>
}